language: python
cache: pip
python:
  - "3.6"
  - "3.7-dev"
env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1
    - TEST_DATABASE_URI="postgresql://postgres@localhost/travis_ci_test"
    - ELASTICSEARCH_URL="http://localhost:9200"
services:
  - postgresql
  - elasticsearch
# command to install dependencies
install: "make"
# command to run tests
before_script:
  - sleep 10  # allow Elasticsearch to initialize
  - psql -c 'create database travis_ci_test;' -U postgres
  - pipenv run python -m tests.data.setup_testdb
script:
    - make test
