language: python
python:
  - "3.6"
  - "3.7-dev"
env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1
# command to install dependencies
install: "make"
# command to run tests
script:
    - make test
cache: pip
